spring:
  application:
    name: acme

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: tomcat

acme:
  base-url: https://localhost:8443/acme
  nonce:
    max-age: 300        # Nonce 최대 유효 시간 (초) - 기본 5분
    max-count: 1000     # 최대 저장할 Nonce 개수 - 기본 1000개